// <auto-generated />
using Fiap.Api.Energy.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Energy.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260515151316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Fiap.Api.Energy.Models.CustoEquipamentoModel", b =>
                {
                    b.Property<int>("CustoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustoEquipamentoDia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CustoEquipamentoMensal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorKwh")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("CustoId");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("CustosEquipamento", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Energy.Models.EquipamentoModel", b =>
                {
                    b.Property<int>("EquipamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipamentoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsoMinutoDia")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipamentoId");

                    b.ToTable("Equipamentos", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Energy.Models.CustoEquipamentoModel", b =>
                {
                    b.HasOne("Fiap.Api.Energy.Models.EquipamentoModel", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });
#pragma warning restore 612, 618
        }
    }
}
